[mgr]

prepend_keymap = [
	# yazi
	{ on = "C-q",          run = "quit --no-cwd-file",   desc = "Quit without outputting cwd-file" },
	{ on = "<C-w>",        run = "close",                desc = "Close the current tab, or quit if it's last" },
	{ on = ["g", "r"],     run = "cd /",                 desc = "Go to root directory" },

	# sudo
	{ on = ["s", "p"],       run = "plugin sudo -- paste",           desc = "sudo paste" },
	{ on = ["s", "P"],       run = "plugin sudo -- paste --force",   desc = "sudo force paste" },
	{ on = ["s", "r"],       run = "plugin sudo -- rename",          desc = "sudo rename" },
	{ on = ["s", "-"],       run = "plugin sudo -- link",            desc = "sudo symlink absolute path" },
	{ on = ["s", "_"],       run = "plugin sudo -- link --relative", desc = "sudo symlink relative path" },
	{ on = ["s", "<C-->"],   run = "plugin sudo -- hardlink",        desc = "sudo hardlink" },
	{ on = ["s", "a"],       run = "plugin sudo -- create",          desc = "sudo create" },
	{ on = ["s", "d"],       run = "plugin sudo -- remove",          desc = "sudo trash" },
	{ on = ["s", "D"],       run = "plugin sudo -- remove --permanently",          desc = "sudo delete" },
	{ on = ["s", "m"],       run = "plugin sudo -- chmod",           desc = "sudo chmod" },

	# compress
	{ on = ["c", "a", "a"],    run = "plugin compress",      desc = "Archive selected files" },
	{ on = ["c", "a", "p"],    run = "plugin compress -p",   desc = "Archive selected files (password)" },
	{ on = ["c", "a", "h"],    run = "plugin compress -ph",  desc = "Archive selected files (password+header)" },
	{ on = ["c", "a", "l"],    run = "plugin compress -l",   desc = "Archive selected files (compression level)" }, 
	{ on = ["c", "a", "u"],    run = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },

	# rsync
	{ on = "R",        run = "plugin rsync",             desc = "Copy files using rsync" },

	# kde-connect
	{ on = "K",        run = "plugin kdeconnect-send",   desc = "Send selected files via KDE Connect" },

	# smart-enter
	{ on = "<Enter>",  run = "plugin smart-enter",       desc = "Enter the child directory, or open the file" },

	# custom-shell
	{ on = ";", run = 'plugin custom-shell -- auto', desc = "custom-shell as default, interactive" },
	{ on = ":", run = 'plugin custom-shell -- auto --block', desc = "custom-shell as default, interactive, block" },

]


[manager]

prepend_keymap = [
	# time-travel
	{ on = ["<C-b>", "h"], run = "plugin time-travel --args=prev", desc = "Go to previous snapshot" },
	{ on = ["<C-b>", "l"], run = "plugin time-travel --args=next", desc = "Go to next snapshot" },
	{ on = ["<C-b>", "e"], run = "plugin time-travel --args=exit", desc = "Exit browsing snapshots" },
]
