[opener]

edit = [
	{ run = '${EDITOR:-nano} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]

[plugin]

prepend_fetchers = [
	{ id  = "git",    url = "*",    run = "git" },
	{ id  = "git",    url = "*/",   run = "git" },

]
